
# html lang
language: ja

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/cdtckw.css

# scripts loaded in the end of the body
scripts:
- /js/cdtckw.js
- /js/p5js_title.js
